#!/bin/bash

# hostname
hostnamectl hostname ${hostname}

# update
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade

# fail2ban
apt install -y fail2ban
systemctl enable fail2ban
systemctl start fail2ban

# utilities
apt install -y awscli net-tools
